#Texas Instruments AM62 dual core 1GB USB2 DDR4

BOARD_NAME="BeagleBoard.org PocketBeagle 2"
BOARDFAMILY="k3"
BOARD_MAINTAINER="grippy98"
BOOTCONFIG="am6232_pocketbeagle2_a53_defconfig"
BOOTFS_TYPE="fat"
BOOT_FDT_FILE="k3-am6232-pocketbeagle2.dts"
TIBOOT3_BOOTCONFIG="am6232_pocketbeagle2_r5_defconfig"
TIBOOT3_FILE="tiboot3-am62x-hs-fs-evm.bin"
DEFAULT_CONSOLE="serial"
KERNEL_TARGET="beagle-pocketbeagle2-edge"
KERNEL_TEST_TARGET="beagle-pocketbeagle2-edge"
SERIALCON="ttyS2"
ATF_BOARD="lite"
