# Texas Instruments AM62P quad core 8GB DDR4

BOARD_NAME="SK-AM62P"
BOARDFAMILY="k3"
BOARD_MAINTAINER="glneo"
BOOTCONFIG="am62px_evm_a53_defconfig"
BOOTFS_TYPE="fat"
BOOT_FDT_FILE="k3-am62p5-sk.dts"
TIBOOT3_BOOTCONFIG="am62px_evm_r5_defconfig"
TIBOOT3_FILE="tiboot3-am62px-hs-fs-evm.bin"
DEFAULT_CONSOLE="serial"
KERNEL_TARGET="current"
KERNEL_TEST_TARGET="current"
SERIALCON="ttyS2"
ATF_BOARD="lite"
